language: java
jdk:
  - openjdk11

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="5a08372d-fac9-4c90-a27c-b0afb0bbb42e"

notifications:
  email:
    recipients:
      -vanyadiadia@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

